server:
  port: 8088

### 数据库配置
spring:
  datasource:
    url: jdbc:mysql://***:3306/blue_berry_pie?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: ***
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 3000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  ### Redis 配置
  redis:
    host: ***
    port: 6379
    timeout: 5000ms
    password: ****
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  ###RabbitMQ
  rabbitmq:
    host: ***
    port: 5672
    username: guest
    password: ****

  ###邮箱配置
  mail:
    host: smtp.qq.com
    username: ****
    password: ****

#mybatis:
#  ###数据库模型对象
#  type-aliases-package: com.example.blueberrypieapi.entity
#  mapper-locations: mapper/*.xml

mybatis-plus:  # Mybatis-Plus学习官方文档：https://baomidou.oschina.io/mybatis-plus-doc/#/quick-start
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.blueberrypieapi.entity #别名

  global-config:
    db-config:
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)


### jwt
jwt:
  ###过期时间 s数432000 5天
  time: 432000
  ###安全密钥
  secret: "BlueBerryPie"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"
  login: "login_"
  login_time: 1



